version: 2

models:
  # STAGING MODELS
  - name: stg_trading_books
    description: "Cleaned trading book data with essential validations"
    columns:
      - name: trade_id
        description: "Unique trade identifier"
        tests:
          - unique
          - not_null
      - name: trade_date
        description: "Date of the trade"
        tests:
          - not_null
      - name: trader_name
        description: "Name of the trader"
        tests:
          - not_null
      - name: desk
        description: "Trading desk name"
        tests:
          - not_null
          - accepted_values:
              values: ['EQUITIES', 'FIXED_INCOME', 'FX', 'COMMODITIES', 'DERIVATIVES']
      - name: ticker
        description: "Traded instrument"
        tests:
          - not_null
      - name: quantity
        description: "Trade quantity"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: price
        description: "Trade price"  
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: trade_type
        description: "Type of trade (BUY/SELL)"
        tests:
          - not_null
          - accepted_values:
              values: ['BUY', 'SELL']

  - name: stg_stock_metrics
    description: "Cleaned stock market data with OHLC validations"
    columns:
      - name: run_date
        description: "Market data date"
        tests:
          - not_null
      - name: ticker
        description: "Stock ticker symbol"
        tests:
          - not_null
      - name: open_price
        description: "Opening price"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: high_price
        description: "Highest price"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: low_price
        description: "Lowest price"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: close_price
        description: "Closing price"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: volume
        description: "Trading volume"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - run_date
            - ticker

  - name: stg_forex_metrics
    description: "Cleaned forex exchange rate data with validations"
    columns:
      - name: run_date
        description: "Market data date"
        tests:
          - not_null
      - name: currency_pair_name
        description: "Currency pair (e.g., EUR/USD)"
        tests:
          - not_null
      - name: open_rate
        description: "Opening rate"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: high_rate
        description: "Highest rate"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: low_rate
        description: "Lowest rate"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: close_rate
        description: "Closing rate"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - run_date
            - currency_pair_name

  - name: stg_weights
    description: "Portfolio target allocations with validations"
    columns:
      - name: region
        description: "Geographic region"
        tests:
          - not_null
          - accepted_values:
              values: ['NORTH_AMERICA', 'EUROPE', 'ASIA_PACIFIC', 'EMERGING_MARKETS']
      - name: desk
        description: "Trading desk name"
        tests:
          - not_null
          - accepted_values:
              values: ['EQUITIES', 'FIXED_INCOME', 'FX', 'COMMODITIES', 'DERIVATIVES']
      - name: target_allocation
        description: "Target portfolio allocation (should sum to 1.0 per desk)"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0 and <= 1"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - region
            - desk

  # INTERMEDIATE MODELS  
  - name: int_trade_pnl
    description: "Trade-level P&L calculations with validations"
    tests:
      - relationships:
          to: ref('stg_trading_books')
          field: trade_id

  - name: int_equity_trade_pnl
    description: "Equity trade P&L calculations"
    tests:
      - relationships:
          to: ref('int_trade_pnl')
          field: trade_id

  - name: int_fx_trade_pnl
    description: "FX trade P&L calculations"
    tests:
      - relationships:
          to: ref('int_trade_pnl')
          field: trade_id

  # MART MODELS
  - name: fct_data_quality_dashboard
    description: "Comprehensive data quality monitoring dashboard"
    columns:
      - name: data_source
        description: "Source of the data (TRADING_DATA, MARKET_DATA)"
        tests:
          - not_null
          - accepted_values:
              values: ['TRADING_DATA', 'MARKET_DATA']
      - name: data_quality_score
        description: "Quality score from 0-100 (higher is better)"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0 and <= 100"
      - name: failure_severity
        description: "Severity classification of data quality issues"
        tests:
          - accepted_values:
              values: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']

  - name: fct_pnl_by_desk
    description: "P&L aggregated by trading desk"
    columns:
      - name: desk
        description: "Trading desk"
        tests:
          - not_null
          - accepted_values:
              values: ['EQUITIES', 'FIXED_INCOME', 'FX', 'COMMODITIES', 'DERIVATIVES']
      - name: trade_date
        description: "Trade date"
        tests:
          - not_null
      - name: total_pnl
        description: "Total P&L for the desk on the date"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - desk
            - trade_date

  - name: fct_pnl_vs_target
    description: "P&L vs target allocations analysis"
    tests:
      - relationships:
          to: ref('stg_weights')
          field: desk

  - name: fct_trader_drivers
    description: "Key performance indicators for individual traders"
    columns:
      - name: trader_name
        description: "Trader name"
        tests:
          - not_null
    tests:
      - relationships:
          to: ref('stg_trading_books')
          field: trader_name 